spring:
  data:
    mongodb:
#      host: localhost || default
#      port: 27017 || default
      uri: ${MONGODB_URL_DEV}
      uuid-representation: standard
      database: dev
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
server:
  port: 8081
chat:
  message:
    limit: 10
